watersprite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic.base import TemplateView
from entries.views import EntryCreateView
from judging import views as judging

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'watersprite.views.home', name='home'),
    # url(r'^watersprite/', include('watersprite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', EntryCreateView.as_view()),

    url(r'^judging/$', 'judging.views.index', name='judging_index'),
    url(r'^judging/(\d+)$', 'judging.views.entry_rating', name='entry_rating'),
    url(r'^judging/welcome/$', judging.WelcomeInterstitialView.as_view(), name="welcome_interstitial"),

    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout$', 'django.contrib.auth.views.logout', kwargs={'next_page': '/judging'}, name='logout'),

    (r'^conversion_endpoint$', 'entries.views.conversion_endpoint_view')
)

judging/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F
from django.db.models.aggregates import Avg
from django.db.models.signals import post_save
from entries.models import Entry, Genre, Competition


class EntryPackage(models.Model):
    entries = models.ManyToManyField(to=Entry,blank=True)
    judges = models.ManyToManyField(to=User,related_name='entry_packages')
    label = models.CharField(max_length=255, blank=True, help_text="Warning: this label is visible to the judging users")
    def entry_count(self):
        return self.entries.count()
    def entry_list_text(self):
        return '\n'.join([entry.film_name for entry in self.entries.all()])
    def __unicode__(self):
        if self.label:
            return '%s (#%s)' % (self.label, self.id)
        return 'Entry package #%s' % self.id

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        JudgeProfile.objects.create(user=instance)
post_save.connect(create_user_profile, sender=User)

class RatingCriterion(models.Model):
    name = models.CharField(max_length=255)
    genres = models.ManyToManyField(to=Genre,related_name='criteria')
    wildcard_allowed = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.name)

    def get_shortlist(self, include_wildcard=True):
        try:
            current_comp = Competition.objects.latest()
        except Competition.DoesNotExist:
            return

        scores = self.ratingscore_set.filter(rating__entry__competition=current_comp)
        if not include_wildcard:
            scores = scores.filter(wildcard=False)

        shortlist = scores.values('rating__entry').annotate(avg=Avg('score')).order_by('-avg')[:20]
        return [{'entry': Entry.objects.get(id=r['rating__entry']), 'avg': r['avg'], 'wildcard_count': scores.filter(wildcard=True, rating__entry=r['rating__entry']).count()} for r in shortlist]

    class Meta:
        verbose_name_plural = 'rating criteria'

class RatingScore(models.Model):
    criterion = models.ForeignKey(to=RatingCriterion)
    score = models.IntegerField()
    rating = models.ForeignKey(to='Rating')
    wildcard = models.BooleanField(default=False)
    def __unicode__(self):
        return "%s: %s (%s)" % (self.criterion.name, self.score, self.rating.entry.film_name)

    @property
    def is_wildcard(self):
        return self.criterion not in self.rating.entry.award_categories.all()

    def save(self, *args, **kwargs):
        self.wildcard = self.is_wildcard
        return super(RatingScore, self).save(*args, **kwargs)

class Rating(models.Model):
    entry = models.ForeignKey(to=Entry)
    judge = models.ForeignKey(to=User)
    comment = models.TextField()
    overall = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)


class JudgeProfile(models.Model):
    user = models.OneToOneField(to=User,blank=True,null=True)
    entry_package = models.ForeignKey(to=EntryPackage,blank=True,null=True)
    judge_group = models.ForeignKey(to='JudgeGroup', blank=True, null=True)
    is_new = models.BooleanField(default=True)

    @property
    def enable_rating(self):
        if self.judge_group:
            return self.judge_group.enable_rating
        return False

    def __unicode__(self):
        return unicode(self.user.email)

    def has_rated(self, entry):
        return len(Rating.objects.filter(judge=self.user, entry=entry)) > 0

    def has_finished_rating(self):
        if self.entry_package:
            return Rating.objects.filter(judge=self.user, entry__in=self.entry_package.entries.all()).count() == self.entry_package.entries.count()
        return False

class JudgeGroup(models.Model):
    name = models.CharField(max_length=255)
    open_date = models.DateTimeField(blank=True, null=True, help_text="Users will not be able to access the system before this time")
    close_date = models.DateTimeField(blank=True, null=True, help_text="Users will not be able to access the system after this time")
    enable_rating = models.BooleanField(default=True)
    def __unicode__(self):
        return self.name

judging/forms.py
from django import forms
from django.forms.models import ModelForm
from judging.models import Rating

class RatingForm(ModelForm):
    overall = forms.IntegerField(initial=5)
    class Meta:
        model = Rating
        exclude = ['judge', 'entry']

judging/views.py
# Create your views here.
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template.context import RequestContext
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView, CreateView, BaseCreateView
from querystring_parser import parser
from entries.models import Entry, Genre
from judging.models import Rating, RatingCriterion, RatingScore, JudgeProfile

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class LoginRequiredMixin(object):
    u"""Ensures that user must be authenticated in order to access view."""

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


@login_required
def index(request):
    u = request.user
    try:
        if u.get_profile().is_new:
            return redirect('welcome_interstitial')
        entries = u.get_profile().entry_package.entries.all().exclude(rating__judge=u)
    except AttributeError:
        entries = []
    except JudgeProfile.DoesNotExist:
        raise Http404

    context = RequestContext(request)
    context['entries'] = entries
    context['already_rated'] = Entry.objects.filter(rating__judge=u)
    return render_to_response('judging/index.html',context)

@login_required
def entry_rating(request,*args,**kwargs):
    package = request.user.get_profile().entry_package
    try:
        entry = package.entries.get(id=args[0])
    except Entry.DoesNotExist:
        raise Http404()

    if Rating.objects.filter(judge=request.user,entry=entry).count() > 0:
        messages.add_message(request, messages.ERROR, 'Your have already rated that entry')
        return redirect(reverse('judging_index'))

    if request.POST:
        post_dict = parser.parse(request.POST.urlencode())
        r = Rating.objects.create(entry=entry,judge=request.user,comment=request.POST.get('comment',''),overall=request.POST.get('overall',5))
        for x,y in post_dict['criteria'].items():
            c = RatingCriterion.objects.get(id=x)
            RatingScore.objects.create(rating=r,criterion=c,score=y)
        messages.add_message(request, messages.SUCCESS, 'Your rating for %s has been recorded' % entry.film_name)
        print post_dict
        if post_dict.has_key('submit_next'):
            try:
                next = package.entries.exclude(id=entry.id)[0]
                return redirect(reverse('entry_rating',args=(next.id,)))
            except IndexError:
                messages.add_message(request, messages.ERROR, 'You have no more entries to rate!')
                return redirect(reverse('judging_index'))
        else:
            return redirect(reverse('judging_index'))


    genre = Genre.objects.get(shortcode=entry.genre)
    context = RequestContext(request)
    context['entry'] = entry
    context['genre'] = genre
    context['suggest_criteria'] = RatingCriterion.objects.filter(wildcard_allowed=True).exclude(id__in=[rc.id for rc in entry.award_categories.all()])
    return render_to_response('judging/rating.html', context)

class EntryRatingView(LoginRequiredMixin, CreateView):

    template_name = 'judging/rating.html'
    model = Rating

    def get(self, request, *args, **kwargs):
        self.package = request.user.get_profile().entry_package
        try:
            self.entry = self.package.entries.get(id=kwargs.get('eid'))
        except Entry.DoesNotExist:
            raise Http404()
        return super(BaseCreateView,self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.package = request.user.get_profile().entry_package
        try:
            self.entry = self.package.entries.get(id=kwargs.get('eid'))
        except Entry.DoesNotExist:
            raise Http404()
        self.object = self.model(judge=request.user,entry=self.entry)
        return super(BaseCreateView,self).get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        post_dict = parser.parse(self.request.POST.urlencode())
        for x,y in post_dict['criteria'].items():
            c = RatingCriterion.objects.get(id=x)
            RatingScore.objects.create(rating=self.object,criterion=c,score=y)
        messages.add_message(self.request, messages.SUCCESS, 'Your rating for %s has been recorded' % entry.film_name)
        return self.get_success_url()

    def get_success_url(self):
        if self.request.POST.has_key('submit_next'):
            try:
                next = self.package.entries.exclude(id=self.entry.id)[0]
                return reverse('entry_rating',next.id)
            except IndexError:
                messages.add_message(self.request, messages.ERROR, 'You have no more entries to rate!')
                return reverse('judging_index')
        else:
            return redirect(reverse('judging_index'))

    def get_context_data(self, **kwargs):
        context = super(EntryRatingView,self).get_context_data(**kwargs)
        context['entry'] = self.entry
        genre = Genre.objects.get(shortcode=self.entry.genre)
        context['genre'] = genre
        return context

class WelcomeInterstitialView(TemplateView):
    template_name = 'judging/welcome.html'

    def post(self, request, *args, **kwargs):
        if request.POST.get('continue'):
            try:
                jp = request.user.get_profile()
                jp.is_new = False
                jp.save()
            except JudgeProfile.DoesNotExist:
                pass
            return redirect('judging_index')
        else:
            return super(WelcomeInterstitialView,self).get(request, *args, **kwargs)

templates/judging/index.html
{% extends 'base.html' %}
{% block main %}
    <h1>Judging home</h1>
<p>Welcome to the Watersprite judging system.  Your allocated entries are shown below. Click on an entry to view the film{% if user.get_profile.enable_rating %} and record your rating{% endif %}.</p>
    {% if entries %}
    {% if user.get_profile.entry_package.label %}
    <h2>{{ user.get_profile.entry_package.label }}</h2>
    {% endif %}
    <ul>
    {% for e in entries %}
        {% if e.is_complete %}
        <li>
            {% if e.is_converted %}
                <a href="{% url 'entry_rating' e.id %}">
                {{ e }}</a> ({{ e.film_length }})
            {% else %}
                {{ e }}</a> [waiting conversion]
            {% endif %}
        </li>
        {% endif %}
    {% endfor %}
    </ul>
    {% else %}
    <p><b>You have no entries left to rate!</b></p>
    {% endif %}
    {% if already_rated and user.get_profile.enable_rating %}
    <p>Your existing ratings are shown below:</p>
    <ul>
    {% for e in already_rated %}
        <li>{{ e }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <p>If you have any problems, please email <a href="mailto:webmaster@watersprite.org">webmaster@watersprite.org</a></p>
{% endblock %}

templates/judging/rating.html
{% extends 'base.html' %}
{% block main %}
    {% if user.get_profile.enable_rating %}
    <form method="post">
    {% endif %}
    <p><a href="{% url 'judging_index' %}">&laquo; back</a></p>
        <div class="video-player">
            <video width="512" height="384" controls>
                <source src="{{ entry.film_file_converted.url }}" type="video/mp4">
                Your browser does not support the video tag. You must be using Internet Explorer 9, Google Chrome or Apple Safari.
            </video>
        </div>
        <h1>{{ entry.film_name }}</h1>
        <p><strong>Synopsis:</strong> {{ entry.film_synopsis }}</p>
        <p><strong>Genre:</strong> {{ entry.get_genre }}</p>
        <p><a href="{{ entry.film_file_converted.url }}">Advanced</a></p>
    {% if user.get_profile.enable_rating %}
        <div class="rating">
            <label for="id_overall">Overall rating:</label>
            <div class="slider" id="slider_overall"></div>
            <span class="value"><input type="text" name="overall" id="id_overall" value="5" />/10</span>
        </div>
        {% for c in entry.award_categories.all %}
            <div class="rating">
                <label for="id_criteria_{{ c.id }}">{{ c }}:</label>
                <div class="slider" id="slider_{{ c.id }}"></div>
                <span class="value"><input type="text" name="criteria[{{ c.id }}]" id="id_criteria_{{ c.id }}" value="5" />/10</span>
            </div>
        {% endfor %}
        <div class="rating-suggest" id="rating_suggest">
            <div class="select-form">
                <p>Do you feel this film merits consideration in any of these categories? Please note, this is not obligatory and you are free to submit your scores without completing this section.</p>
                {% for c in suggest_criteria %}
                <input type="checkbox" id="rating_suggest_{{ c.id }}" data-criterion-id="{{ c.id }}" />
                    <label for="rating_suggest_{{ c.id }}">{{ c.name }}</label>
                {% endfor %}
            </div>

        </div>
        <br clear="all" />
            {% csrf_token %}
            <label for="id_comment">Comment:</label>
            <textarea name="comment" id="id_comment"></textarea>
        <div>
            <button type="submit" name="submit">Submit</button>
            <button type="submit" name="submit_next">Submit and next</button>
        </div>
        </form>

        <script type="text/javascript">
        $(function() {
            var sliderConfig = function(s) {
                return {
                    value: 5,
                    min: 1,
                    max: 10,
                    step: 1,
                    slide: function( event, ui ) {
                        s.parent().find('input').val(ui.value);
                    }
            }
            };
            $('.slider').each(function() {
                $(this).slider(sliderConfig($(this)));
            });

            $('form').submit(function() {
                if ($('#id_comment').val() == '') {
                    alert('You must enter a comment');
                    return false;
                }
            });

            $('#rating_suggest').find('input[type=checkbox]').change(function() {
                var cname = $('label[for='+this.id+']').html();
                var cid = $(this).data('criterion-id');
                if (this.checked) {
                    // Add a new box
                    var newRating = $('.rating').first().clone();
                    newRating.find('.slider').remove();
                    newRating.find('label').attr('for','id_criteria_'+cid)
                            .html(cname);
                    $("<div class='slider'></div>").insertAfter(newRating.find('label'));
                    newRating.find('input').attr('id','id_criteria_'+cid)
                            .attr('name','criteria['+cid+']');
                    newRating.attr('id', 'rating_cid_'+cid)
                            .appendTo('#rating_suggest').hide().fadeIn()
                            .find('.slider').slider(sliderConfig(newRating.find('.slider')));
                } else {
                    $('#rating_cid_'+cid).fadeOut( function() { $(this).remove() });
                }
            })
        });
        </script>
    {% endif %}
{% endblock %}

templates/judging/welcome.html
{% extends 'base.html' %}

{% block main %}

    <div class="judging-welcome">
        <div class="overlay" id="judging_welcome_overlay">
            <a class="close-button" href="#" id="close_button">&times;</a>
        </div>

        <iframe src="http://player.vimeo.com/video/81878866?color=ffffff&amp;autoplay=1" width="896" height="504" frameborder="0"
                webkitallowfullscreen mozallowfullscreen allowfullscreen autoplay class="judging-welcome-video"></iframe>

        <div class="continue">
            <form action="" method="post">
            {% csrf_token %}
                <button type="submit" name="continue" value="continue">Continue to portal <span class="icon icon-chevron-right"></span></button>
            </form>
        </div>

    </div>


    <script type="text/javascript">

    $(function() {
        var $f = $('iframe'),
            url = $f.attr('src').split('?')[0];

        // Helper function nicked off vimeo website
        function post(action, value) {
            var data = { method: action };

            if (value) {
                data.value = value;
            }

            $f[0].contentWindow.postMessage(JSON.stringify(data), url);
        }

        function hideOverlay() {
            $('#judging_welcome_overlay').hide('fade', 2000);
            post('pause');
        }

        function showOverlay() {
            $('#judging_welcome_overlay').show('fade', 2000);
            post('play');
        }

        function onMessageReceived(e) {
            var data = JSON.parse(e.data);

            console.log(data);
            switch (data.event) {
                case 'ready':
                    post('addEventListener', 'pause');
                    post('addEventListener', 'play');
                    post('addEventListener', 'finish')
                    break;

                case 'play':
                    showOverlay();
                    break;

                case 'finish':
                    hideOverlay();

            }
        }

        if (window.addEventListener) {
            window.addEventListener('message', onMessageReceived, false);
        }
        else {
            window.attachEvent('onmessage', onMessageReceived, false);
        }


        $('#close_button').click(hideOverlay)
    });


    </script>

{% endblock %}